### ISSUE TITLE
Handling file uploads

### ISSUE THREAD

**Issue by bshishov** [LukasBoersma/FastCGI#1] opened 2016-02-01 13:14 UTC
Hello, 
I'm getting stuck trying to receive file uploads. Can you please provide some information of how to do this? 
Or maybe provide some sort of request stream to the request object?
Because files are often sent using enctype="multipart/form-data" is it possible not to load request.body with the whole data?

As i figured out that it appears at `Request.HandleRecord(Record)`

```
case Record.RecordType.Stdin:
    string data = Encoding.ASCII.GetString(record.ContentData);
    Body += data;
```

new data just concatenates as string, but how to deal with large binary files?

P.S. Can you please also remove Console.Writeline calls? Because they are interrupting actual application output, and i have no idea how to supress it :)

**Comment by LukasBoersma** [comment] 2016-02-02 08:24
Hi,

sure, I will have a look at this. To be honest, when I started writing this library, I just read through the FastCGI specification and had no idea how HTTP works. I think it should be possible to provide a stream for the request data. And of course there should be a way to get the raw content bytes.

I am a bit busy at the moment, I hope I will get back to you with a solution by the end  of the week.

> Can you please also remove Console.Writeline calls?

Whoops, those writelines slipped through in my commits. Will remove them.

**Comment by LukasBoersma** [comment] 2016-02-02 10:32
Okay, I have a first version on the new [body-stream](https://github.com/LukasBoersma/FastCGI/tree/body-stream) branch.

The `Request.Body` property has been replaced by ` string GetBody(encoding)` and ` byte[] GetBody()`.

I introduced `Request.RequestBodyStream`, which streams the raw body data. You can use `FCGIApplication.OnRequestIncoming` to be notified about new requests and then start reading the content before the request has been fully transmitted. Alternatively, just parse through the `OpenRequest` list and look for new data.

Here is a quick example:
````csharp
var app = new FCGIApplication();
app.OnRequestIncoming += (sender, request) =>
{
    Console.WriteLine("New request: #{0}", request.RequestId);
};

app.OnRequestReceived += (sender, request) => {
    request.WriteResponseASCII("HTTP/1.1 200 OK\n\nOk");
    request.Close();
};

app.Listen(19000);

while (true)
{
    var didSomething = app.Process();
    if(!didSomething)
        Thread.Sleep(1);
    
    foreach (var request in app.OpenRequests.Values)
    {
        if (request.RequestBodyStream.Length > request.RequestBodyStream.Position)
        {
            Console.WriteLine("Received new data for request #{0}: {1} bytes", request.RequestId, request.RequestBodyStream.Length);
        }
    }
}
````

All this is totally untested. Could you check it out and tell me if it works for you?

**Comment by bshishov** [comment] 2016-02-02 10:57
I'll check it out today

**Comment by LukasBoersma** [comment] 2016-02-02 11:43
Ah sorry, commit is pushed now.

**Comment by bshishov** [comment] 2016-02-02 23:32
Well, the execution never enters foreach body. So there are no open requests at that point. But `RequestBodyStream` works fine. 

I'm testing file uploading/submitiing forms with curl:
    curl -i -X POST -F "foo=bar" -F "file=@somefile.txt" localhost:88
`-F` specifies that it is a multipart POST form

But after some more 'tests' with larger files (e.g. 1.4Mb, it's need to set `client_max_body_size` in nginx config to handle this request) the whole thing refuses to work correctly. 

it happens here:

    if (r.Version != Constants.FCGI_VERSION_1)
                    throw new InvalidDataException("Invalid version number in FastCGI record header. Possibly corrupted data.");

so the record cannot be parsed. I think that this is happening when input stream doesn't pass a record, only a part of it, beacuse nginx splits large record (which length is > than some stream buffer) into several parts, and only a first may be parsed as a record, or something like that.

**Comment by LukasBoersma** [comment] 2016-02-03 12:11
Hm, I can't reproduce that error. Works for me with files >70MB. Are you using Windows .NET or Mono/Linux?

Nginx should split large requests into multiple stdin records (max size for a single record is 64KB). 
In the FastCGI protocol, everything should be a record, so sending raw data without that version number in the record header would be illegal.

Do any files above 64KB work for you? If not, the issue is likely somewhere with the request being split up into multiple records.

**Comment by bshishov** [comment] 2016-02-03 13:12
I'm using Windows .Net (VS2015) and latest stable nginx runnig on same machine.Will test later on linux machine.

Well, uploading my 1.4MB file (some photoshop document) works time to time. So i can "upload" successfully 3 times in row sometimes and on the 4th time get an exception. But sometimes it couldn't upload even for the first time. But it works fine with small (<64KB) files.
Try to send same file several times.

I have no idea now.

**Comment by bshishov** [comment] 2016-02-15 14:39
I've tested on linux machine using mono (**same executable**)

   mono fastcgisample.exe

and that worked **perfectly** even for multiple file sending. But same executable causes error i've described befor (can't parse a record) on windows, idk why.

            var app = new FCGIApplication();
            app.OnRequestIncoming += (sender, request) =>
            {
                Console.WriteLine("New request: #{0}", request.RequestId);                
            };

            app.OnRequestReceived += (sender, request) => {
                request.WriteResponseASCII("HTTP/1.1 200 OK\n\nOk");                
                Console.WriteLine("Received length: {0}", request.RequestBodyStream.Length);
                request.Close();
            };

            app.Run(19000);

Nginx config mentioned before is same for both machines i've tested on.

**Comment by LukasBoersma** [comment] 2017-09-17 16:19
I still can't reproduce it, so I am closing this now. 

I assume this is too long ago to still be an issue for you, but feel free to open a new issue in case you have new info for this.

**Closed by LukasBoersma** 2017-09-17 16:19 UTC
